#!/usr/bin/env python3
"""Regenerate ace_enterprise's own dependency graph: AST-scan src/, resolve
internal imports, persist .ace/architecture_graph.json, and render a
mermaid flowchart to docs/ARCHITECTURE_GRAPH.md.

Manual, on-demand -- not wired into the pre-commit hook, matching
generate_live_docs.py / generate_live_context.py's existing convention
(CLAUDE.md). Run after src/ changes when you actually want an updated
graph, not on every commit.

Usage:
    .venv/bin/python generate_dependency_graph.py
    .venv/bin/python generate_dependency_graph.py --blast-radius src/agents/podman_runner.py
"""
import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from src.utils.dependency_graph import (
    MANIFEST_RELPATH,
    blast_radius,
    build_order,
    has_cycle,
    save,
    scan,
    to_mermaid_flowchart,
)

REPO_ROOT = Path(__file__).parent
SRC_ROOT = REPO_ROOT / "src"
GRAPH_DOC_PATH = REPO_ROOT / "docs" / "ARCHITECTURE_GRAPH.md"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--blast-radius", metavar="MODULE_PATH",
        help="Print the blast radius for one module (e.g. src/agents/podman_runner.py) and exit "
             "without writing anything.",
    )
    args = parser.parse_args()

    print(f"Scanning {SRC_ROOT} ...")
    graph = scan(SRC_ROOT, repo_root=REPO_ROOT)
    print(f"  {len(graph.modules)} modules")

    if args.blast_radius:
        if args.blast_radius not in graph.modules:
            print(f"error: {args.blast_radius!r} not found in the scanned graph", file=sys.stderr)
            sys.exit(1)
        radius = sorted(blast_radius(graph, args.blast_radius))
        print(f"\nblast radius of {args.blast_radius} ({len(radius)} module(s)):")
        for path in radius:
            print(f"  {path}")
        return

    cycle = has_cycle(graph)
    if cycle:
        print(f"  WARNING: cycle detected: {' -> '.join(cycle)}")
    else:
        order = build_order(graph)
        print(f"  acyclic, {len(order)} modules in build order")

    manifest_path = REPO_ROOT / MANIFEST_RELPATH
    save(graph, manifest_path)
    print(f"Wrote {manifest_path}")

    GRAPH_DOC_PATH.parent.mkdir(parents=True, exist_ok=True)
    mermaid = to_mermaid_flowchart(graph)
    doc = (
        "<!-- Generated by generate_dependency_graph.py -- do not edit by hand -->\n\n"
        "# Architecture Dependency Graph\n\n"
        f"{len(graph.modules)} modules scanned from `src/`, "
        f"{'a cycle was found: ' + ' -> '.join(cycle) if cycle else 'acyclic'}.\n\n"
        "Deterministically derived from real `import` statements (AST-parsed), "
        "not hand-maintained or LLM-narrated -- see `src/utils/dependency_graph.py`.\n\n"
        "```mermaid\n"
        f"{mermaid}\n"
        "```\n"
    )
    GRAPH_DOC_PATH.write_text(doc)
    print(f"Wrote {GRAPH_DOC_PATH}")


if __name__ == "__main__":
    main()
