Feature: Decision Record generation
  As a caller building institutional knowledge documentation
  I want to create and persist architectural decision records
  So that feature decisions are captured in a consistent markdown format

  Scenario: Rendering a minimal decision record to markdown
    Given a DecisionRecord with feature_name "Login Rate Limiter" and date "2026-08-15"
    When I call to_markdown on the record
    Then the output contains the heading "# Login Rate Limiter"
    And the output contains "**Date:** 2026-08-15"
    And the output contains "**Status:** Accepted"
    And the output contains "## Context"
    And the output contains "## Decision"
    And the output contains "## Implementation"
    And the output ends with "*Generated by ACE Enterprise - Institutional Knowledge Development Middleware*"

  Scenario: Rendering a fully populated decision record to markdown
    Given a DecisionRecord with feature_name "Payment Retry"
    And requirement "Retries must not double-charge the customer"
    And gherkin_scenarios "Scenario: retry does not duplicate charge"
    And implementation_summary "Added idempotency key to retry logic"
    And design_decisions containing "Used idempotency keys"
    And files_created containing "src/payments/retry.py"
    And tests_generated containing "test_retry_idempotent"
    And patterns_applied containing "Idempotency key pattern"
    And patterns_learned containing "Retries need dedupe tokens"
    And human_contributor "Jane Doe"
    And ai_models containing "claude-sonnet-5"
    When I call to_markdown on the record
    Then the output contains "**Author:** Jane Doe"
    And the output contains "**AI Models:** claude-sonnet-5"
    And the output contains "**Requirement:** Retries must not double-charge the customer"
    And the output contains a fenced "gherkin" code block with "Scenario: retry does not duplicate charge"
    And the output contains "Added idempotency key to retry logic"
    And the output contains "- Used idempotency keys"
    And the output contains "- \`src/payments/retry.py\`"
    And the output contains "- \`test_retry_idempotent\`"
    And the output contains "## Patterns"
    And the output contains "**Applied:**"
    And the output contains "- Idempotency key pattern"
    And the output contains "**Learned:**"
    And the output contains "- Retries need dedupe tokens"

  Scenario: Omitting optional sections when no patterns are supplied
    Given a DecisionRecord with feature_name "Simple Toggle" and no patterns_applied or patterns_learned
    When I call to_markdown on the record
    Then the output does not contain "## Patterns"

  Scenario: Saving a decision record with an auto-generated filename
    Given a DecisionRecord with feature_name "User Onboarding Flow" and date "2026-08-15"
    And an empty target directory ".ace/decisions"
    When I call save with that directory and no filename
    Then a file named "2026-08-15-user-onboarding-flow.md" exists in ".ace/decisions"
    And the file's contents equal the record's to_markdown output
    And the save call returns the path to that file

  Scenario: Saving a decision record with an explicit filename
    Given a DecisionRecord with feature_name "User Onboarding Flow"
    And an empty target directory ".ace/decisions"
    When I call save with that directory and filename "custom-name.md"
    Then a file named "custom-name.md" exists in ".ace/decisions"

  Scenario: Saving creates missing parent directories
    Given a DecisionRecord with feature_name "Cache Warmup"
    And a target directory ".ace/decisions/nested/path" that does not yet exist
    When I call save with that directory
    Then the directory ".ace/decisions/nested/path" is created
    And the ADR file is written inside it

  Scenario: Feature names with spaces and underscores are slugified for the filename
    Given a DecisionRecord with feature_name "My_Cool Feature" and date "2026-08-15"
    And an empty target directory ".ace/decisions"
    When I call save with that directory and no filename
    Then a file named "2026-08-15-my-cool-feature.md" exists in ".ace/decisions"

  Scenario: Generating an ADR from a TDD result
    Given feature_name "Search Autocomplete"
    And gherkin_content "Scenario: user sees suggestions"
    And files_created list containing "src/search/autocomplete.py"
    And tests_generated list containing "test_autocomplete_suggestions"
    And patterns_learned list containing "Debounce input events"
    And human_contributor "Alex Kim"
    And ai_models list containing "claude-sonnet-5"
    When I call generate_adr_from_tdd_result with these values
    Then the returned record has status "Accepted"
    And the returned record's implementation_summary equals "Built Search Autocomplete feature using Gherkin-driven TDD"
    And the returned record's design_decisions include "Used Test-Driven Development (RED → GREEN → REFACTOR)"
    And the returned record's gherkin_scenarios equals "Scenario: user sees suggestions"
    And the returned record's date is set to the current date and time