"""Decision Record (ADR) generation - document what was built and why."""

import logging
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

logger = logging.getLogger(__name__)


@dataclass
class DecisionRecord:
    """Architectural Decision Record for a feature."""

    # Metadata
    feature_name: str
    date: datetime

    # Context
    gherkin_scenarios: str | None = None
    requirement: str | None = None

    # Decision
    implementation_summary: str = ""
    tests_generated: list[str] = None
    files_created: list[str] = None

    # Rationale
    design_decisions: list[str] = None
    patterns_applied: list[str] = None
    patterns_learned: list[str] = None

    # Status
    status: str = "Accepted"  # "Proposed" | "Accepted" | "Deprecated"

    # Contributors
    human_contributor: str | None = None
    ai_models: list[str] = None

    def __post_init__(self):
        """Initialize empty lists."""
        if self.tests_generated is None:
            self.tests_generated = []
        if self.files_created is None:
            self.files_created = []
        if self.design_decisions is None:
            self.design_decisions = []
        if self.patterns_applied is None:
            self.patterns_applied = []
        if self.patterns_learned is None:
            self.patterns_learned = []
        if self.ai_models is None:
            self.ai_models = []

    def to_markdown(self) -> str:
        """Generate ADR in markdown format."""
        # Create slug from feature name
        slug = self.feature_name.lower().replace(' ', '-').replace('_', '-')
        date_str = self.date.strftime('%Y-%m-%d')

        md = []

        # Header
        md.append(f"# {self.feature_name}")
        md.append(f"\n**Date:** {date_str}")
        md.append(f"**Status:** {self.status}")
        if self.human_contributor:
            md.append(f"**Author:** {self.human_contributor}")
        if self.ai_models:
            md.append(f"**AI Models:** {', '.join(self.ai_models)}")
        md.append("")

        # Context
        md.append("## Context")
        md.append("")
        if self.requirement:
            md.append(f"**Requirement:** {self.requirement}")
            md.append("")

        if self.gherkin_scenarios:
            md.append("**Gherkin Scenarios:**")
            md.append("```gherkin")
            md.append(self.gherkin_scenarios)
            md.append("```")
            md.append("")

        # Decision
        md.append("## Decision")
        md.append("")
        if self.implementation_summary:
            md.append(self.implementation_summary)
            md.append("")

        if self.design_decisions:
            md.append("**Design Decisions:**")
            for decision in self.design_decisions:
                md.append(f"- {decision}")
            md.append("")

        # Implementation
        md.append("## Implementation")
        md.append("")

        if self.files_created:
            md.append("**Files Created:**")
            for file in self.files_created:
                md.append(f"- `{file}`")
            md.append("")

        if self.tests_generated:
            md.append("**Tests Generated:**")
            for test in self.tests_generated:
                md.append(f"- `{test}`")
            md.append("")

        # Patterns
        if self.patterns_applied or self.patterns_learned:
            md.append("## Patterns")
            md.append("")

            if self.patterns_applied:
                md.append("**Applied:**")
                for pattern in self.patterns_applied:
                    md.append(f"- {pattern}")
                md.append("")

            if self.patterns_learned:
                md.append("**Learned:**")
                for pattern in self.patterns_learned:
                    md.append(f"- {pattern}")
                md.append("")

        # Footer
        md.append("---")
        md.append("")
        md.append("*Generated by ACE Enterprise - Institutional Knowledge Development Middleware*")

        return "\n".join(md)

    def save(self, directory: Path, filename: str | None = None) -> Path:
        """Save ADR to file.

        Args:
            directory: Directory to save ADR (usually .ace/decisions/)
            filename: Optional filename (auto-generated if not provided)

        Returns:
            Path to saved file
        """
        directory.mkdir(parents=True, exist_ok=True)

        if not filename:
            # Generate filename: YYYY-MM-DD-feature-name.md
            date_str = self.date.strftime('%Y-%m-%d')
            slug = self.feature_name.lower().replace(' ', '-').replace('_', '-')
            filename = f"{date_str}-{slug}.md"

        filepath = directory / filename

        # Write markdown
        filepath.write_text(self.to_markdown())

        logger.info(f"Saved ADR to: {filepath}")
        return filepath


def generate_adr_from_tdd_result(
    feature_name: str,
    gherkin_content: str | None,
    files_created: list[str],
    tests_generated: list[str],
    patterns_learned: list[str],
    human_contributor: str | None = None,
    ai_models: list[str] | None = None
) -> DecisionRecord:
    """Generate ADR from TDD result.

    Args:
        feature_name: Name of feature built
        gherkin_content: Gherkin scenarios (if used)
        files_created: List of files created
        tests_generated: List of test functions generated
        patterns_learned: Patterns learned during TDD
        human_contributor: Human who initiated the build
        ai_models: AI models used

    Returns:
        DecisionRecord ready to save
    """
    return DecisionRecord(
        feature_name=feature_name,
        date=datetime.now(),
        gherkin_scenarios=gherkin_content,
        implementation_summary=f"Built {feature_name} feature using Gherkin-driven TDD",
        files_created=files_created,
        tests_generated=tests_generated,
        design_decisions=[
            "Used Test-Driven Development (RED → GREEN → REFACTOR)",
            "Gherkin scenarios mapped to unit tests",
            "Incremental implementation driven by failing tests"
        ],
        patterns_learned=patterns_learned,
        status="Accepted",
        human_contributor=human_contributor,
        ai_models=ai_models or []
    )
